//
//  RenderNode+Context.swift
//  PyNucleantUI
//
import QuartzCore
import SulphurVulkan
import VulkanCore
import CVulkan
import SulphurCore
import SulphurShader
import CWgpu
#if canImport(SulphurApplication)
import SulphurApplication
#endif

// later on / generated by some yaml file + BuildToolPlugin
// and generates the final RenderEnum
extension RenderNode {
    // generated later on
    public enum Context {
        case thor(ThorShaderNode)
        case skia(SkiaShaderNode)
        case shader(OGLShaderNode)
        case group(GroupNode)
    }
    
}

