import QuartzCore
import SulphurVulkan
import VulkanCore
import CVulkan
import SulphurCore
import SulphurShader
import CWgpu
#if canImport(SulphurApplication)
import SulphurApplication
#endif


// MARK: - Node type







public struct RenderNode {
    let id: Int
    
    let context: Context
    
    init(id: Int, context: Context) {
        self.id = id
        self.context = context
    }
}

public final class GroupNode {
    var nodes: [RenderNode]
    
    init(nodes: [RenderNode]) {
        self.nodes = nodes
    }
}

// later on / generated by some yaml file + BuildToolPlugin
// and generates the final RenderEnum
extension RenderNode {
    // generated later on
    public enum Context {
        case thor(ThorShaderNode)
        case skia(SkiaShaderNode)
        case shader(OGLShaderNode)
        case group(GroupNode)
    }
    
}