//
//  RenderNode+Context.swift
//  PyNucleantUI
//
import QuartzCore
import NucleantVulkan
import VulkanCore
import CVulkan
//import NucleantVulkan
import SulphurShader
import CWgpu
#if canImport(SulphurApplication)
import SulphurApplication
#endif

// later on / generated by some yaml file + BuildToolPlugin
// and generates the final RenderEnum
extension RenderNode {
    // generated later on
    public enum Context {
        case thor(ThorShaderNode)
        case skia(SkiaShaderNode)
        case shader(OGLShaderNode)
        case pixel_buffer(PixelBufferShaderNode)
        case group(GroupNode)
        case texture_group(TextureGroupNode)
    }
    
}

